import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import { WagmiAppProvider } from "@/components/wagmi-provider";
import { AppQueryClientProvider } from "@/query-client-provider";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const dmsans = DM_Sans({
    variable: "--font-dm-sans",
    weight: ["400", "500", "700"],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${dmsans.variable} antialiased`}>
                <WagmiAppProvider>
                    <AppQueryClientProvider>
                        {children}
                    </AppQueryClientProvider>
                </WagmiAppProvider>
            </body>
        </html>
    );
}
