import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import { WagmiAppProvider } from "@/components/wagmi-provider";
import { AppQueryClientProvider } from "@/query-client-provider";
import "@rainbow-me/rainbowkit/styles.css";
import { Toaster } from "@/components/ui/toaster";
import { RainbowKitProvider } from "@rainbow-me/rainbowkit";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dmsans = DM_Sans({
  variable: "--font-dm-sans",
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmsans.variable} antialiased`}>
        {" "}
        <WagmiAppProvider>
          <AppQueryClientProvider>
            <RainbowKitProvider>
              {children}
              <Toaster />
            </RainbowKitProvider>
          </AppQueryClientProvider>
        </WagmiAppProvider>
      </body>
    </html>
  );
}
